require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/categories", type: :request do
  before :each do
    @user = User.create(name: 'Test', email: 'test2@example.com', password: 'password')
    @product = Product.create(author: @user, name: 'test product', icon: 'https://www.ikea.com/images/grimsloev-series-in-off-white-54161e19bd8d6fb3df81e6c9b84efaae.jpg')
    sign_in @user
  end
  describe 'GET /new' do
    it 'returns http success' do
      get new_product_category_path(@product)
      expect(response).to have_http_status(:success)
    end
  end

  describe 'POST :create' do
    it 'creates a new category' do
      category_attributes = { name: 'test product', amount: 20 }

      post product_categories_path(@product), params: { category: category_attributes }

      expect(response.status).to eq(302)
      expect(Category.last.name).to eq('test category')
      expect(Category.last.amount).to eq(20.0)
    end
  end
end