require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/products_categories", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ProductsCategory. As you add validations to ProductsCategory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ProductsCategory.create! valid_attributes
      get products_categories_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      products_category = ProductsCategory.create! valid_attributes
      get products_category_url(products_category)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_products_category_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      products_category = ProductsCategory.create! valid_attributes
      get edit_products_category_url(products_category)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ProductsCategory" do
        expect {
          post products_categories_url, params: { products_category: valid_attributes }
        }.to change(ProductsCategory, :count).by(1)
      end

      it "redirects to the created products_category" do
        post products_categories_url, params: { products_category: valid_attributes }
        expect(response).to redirect_to(products_category_url(ProductsCategory.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ProductsCategory" do
        expect {
          post products_categories_url, params: { products_category: invalid_attributes }
        }.to change(ProductsCategory, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post products_categories_url, params: { products_category: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested products_category" do
        products_category = ProductsCategory.create! valid_attributes
        patch products_category_url(products_category), params: { products_category: new_attributes }
        products_category.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the products_category" do
        products_category = ProductsCategory.create! valid_attributes
        patch products_category_url(products_category), params: { products_category: new_attributes }
        products_category.reload
        expect(response).to redirect_to(products_category_url(products_category))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        products_category = ProductsCategory.create! valid_attributes
        patch products_category_url(products_category), params: { products_category: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested products_category" do
      products_category = ProductsCategory.create! valid_attributes
      expect {
        delete products_category_url(products_category)
      }.to change(ProductsCategory, :count).by(-1)
    end

    it "redirects to the products_categories list" do
      products_category = ProductsCategory.create! valid_attributes
      delete products_category_url(products_category)
      expect(response).to redirect_to(products_categories_url)
    end
  end
end
